let DATA=null;
const RELATORIO_VERSAO='10.7';
const MESES={'Janeiro':1,'Fevereiro':2,'Março':3,'Abril':4,'Maio':5,'Junho':6,'Julho':7,'Agosto':8,'Setembro':9,'Outubro':10,'Novembro':11,'Dezembro':12};
const MESES_NUM={'01':'Janeiro','02':'Fevereiro','03':'Março','04':'Abril','05':'Maio','06':'Junho','07':'Julho','08':'Agosto','09':'Setembro','10':'Outubro','11':'Novembro','12':'Dezembro'};
const $=id=>document.getElementById(id);
const texto=v=>v===undefined||v===null?'':String(v);
const safe=v=>texto(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const badge=(t,c)=>t?`<span class="badge ${c}">${safe(t)}</span>`:'';
const vazio=t=>`<p class="empty">${safe(t||'Sem registros para a competência selecionada.')}</p>`;
const metric=(n,v)=>`<div class="metric"><span>${safe(n)}</span><strong>${safe(v)}</strong></div>`;
function mesAnoValor(m){const p=texto(m).split('/');return (Number(p[1])||0)*100+(MESES[p[0]]||0)}
function mesesDeTexto(v){const s=texto(v),out=[];for(const d of s.matchAll(/(\d{2})\/(\d{2})\/(\d{4})/g)){out.push((MESES_NUM[d[2]]||'')+'/'+d[3])}for(const n of s.matchAll(/(Janeiro|Fevereiro|Março|Abril|Maio|Junho|Julho|Agosto|Setembro|Outubro|Novembro|Dezembro)\/(\d{4})/g)){out.push(n[1]+'/'+n[2])}return [...new Set(out.filter(Boolean))]}
function temMes(valor,mes){return mesesDeTexto(valor).includes(mes)||texto(valor)===mes}
function projetoConcluido(p){return /concluído|concluido|finalizado|finalizada/i.test(texto(p.status))}
function listaItens(arr,render,msg){return arr.length?arr.map(render).join(''):vazio(msg)}
function renomearReferencias(data,antigo,novo){const trocar=(obj,campos)=>campos.forEach(c=>{if(obj&&obj[c]===antigo)obj[c]=novo});(data.tarefasConcluidas||[]).forEach(x=>trocar(x,['projeto']));(data.pendencias||[]).forEach(x=>trocar(x,['projeto']));(data.prazos||[]).forEach(x=>trocar(x,['projeto']));const pe=data.proximasEntregas||{};['proximos15Dias','emAndamento','concluidosRecentemente'].forEach(k=>(pe[k]||[]).forEach(x=>trocar(x,['projeto'])))}
function aplicarExtras(data,extra){extra=extra||{};data.projetos=data.projetos||[];data.tarefasConcluidas=data.tarefasConcluidas||[];data.pendencias=data.pendencias||[];data.proximasEntregas=data.proximasEntregas||{};data.proximasEntregas.proximos15Dias=data.proximasEntregas.proximos15Dias||[];data.proximasEntregas.emAndamento=data.proximasEntregas.emAndamento||[];data.proximasEntregas.concluidosRecentemente=data.proximasEntregas.concluidosRecentemente||[];
(extra.ajustesProjetos||[]).forEach(a=>{const p=data.projetos.find(x=>x.nome===a.nomeOriginal||x.nome===a.nome);if(!p)return;const antigo=p.nome;if(a.nome)p.nome=a.nome;if(a.objetivo)p.objetivo=a.objetivo;if(a.ultimaAtualizacao)p.ultimaAtualizacao=a.ultimaAtualizacao;if(a.area)p.area=a.area;if(a.categoria)p.categoria=a.categoria;p.atividades=p.atividades||[];(a.atividadesSubstituir||[]).forEach(s=>{p.atividades=p.atividades.map(x=>x===s.de?s.para:x)});(a.atividadesRemover||[]).forEach(r=>{p.atividades=p.atividades.filter(x=>x!==r)});(a.atividadesAdicionar||[]).forEach(at=>{if(!p.atividades.includes(at))p.atividades.push(at)});if(antigo!==p.nome)renomearReferencias(data,antigo,p.nome)});
(extra.projetos||[]).forEach(p=>{if(!data.projetos.some(x=>x.nome===p.nome))data.projetos.push(p)});
(extra.tarefasConcluidasRemover||[]).forEach(r=>{data.tarefasConcluidas=data.tarefasConcluidas.filter(x=>!(x.projeto===r.projeto&&(!r.data||x.data===r.data)))});
(extra.tarefasConcluidas||[]).forEach(t=>{if(!data.tarefasConcluidas.some(x=>x.projeto===t.projeto&&x.data===t.data&&x.tarefa===t.tarefa))data.tarefasConcluidas.push(t)});
(extra.pendencias||[]).forEach(p=>{if(!data.pendencias.some(x=>x.projeto===p.projeto&&x.pendencia===p.pendencia))data.pendencias.push(p)});
(extra.concluidosRecentementeRemover||[]).forEach(r=>{data.proximasEntregas.concluidosRecentemente=data.proximasEntregas.concluidosRecentemente.filter(x=>!(x.projeto===r.projeto&&(!r.data||x.data===r.data)))});
(extra.concluidosRecentemente||[]).forEach(e=>{if(!data.proximasEntregas.concluidosRecentemente.some(x=>x.projeto===e.projeto&&x.data===e.data&&x.entrega===e.entrega))data.proximasEntregas.concluidosRecentemente.unshift(e)});
data.proximasEntregas.proximos15Dias=data.proximasEntregas.proximos15Dias.filter(x=>!(x.data==='03/06/2026'&&texto(x.entrega).includes('AURA de disparos')));
if(extra.versaoExtra)data.versao=extra.versaoExtra;if(extra.ultimaAtualizacaoExtra)data.ultimaAtualizacao=extra.ultimaAtualizacaoExtra;if(extra.observacaoExtra)data.observacao=extra.observacaoExtra;return data}
function areas(data){return [...new Set((data.projetos||[]).map(p=>p.area||'OUTROS'))]}
function frenteDoProjeto(nome){const p=(DATA.projetos||[]).find(x=>texto(nome).includes(x.nome)||x.nome.includes(texto(nome)));return p?.area||'OUTROS'}
function mesesDoProjeto(p){let ms=[];[p.inicio,p.ultimaAtualizacao,p.previsaoConclusao,p.competencia].forEach(v=>ms.push(...mesesDeTexto(v)));(p.atividades||[]).forEach(a=>ms.push(...mesesDeTexto(a)));return [...new Set(ms)]}
function renderAtividades(tarefas){const grupos={};areas(DATA).concat(['OUTROS']).forEach(a=>grupos[a]=[]);tarefas.forEach(t=>{const f=frenteDoProjeto(t.projeto);(grupos[f]||(grupos[f]=[])).push(t)});return `<div class="front-grid">${Object.keys(grupos).filter(f=>grupos[f].length).map(f=>`<article class="area-panel"><h3>${safe(f)}</h3>${listaItens(grupos[f],t=>`<div class="item"><b>${safe(t.tarefa)}</b><div class="meta">${safe(t.data)}<br>${safe(t.projeto)}<br>Responsável: ${safe(t.responsavel)}</div>${badge(t.status,'ok')}</div>`,'Sem atividades realizadas nesta frente.')}</article>`).join('')||vazio('Sem atividades realizadas para a competência.')}</div>`}
function renderProjetos(projetos){const ativos=projetos.filter(p=>!projetoConcluido(p));const grupos={};areas(DATA).concat(['OUTROS']).forEach(a=>grupos[a]=[]);ativos.forEach(p=>(grupos[p.area||'OUTROS']||(grupos[p.area||'OUTROS']=[])).push(p));return `<div class="front-grid">${Object.keys(grupos).filter(f=>grupos[f].length).map(f=>`<article class="area-panel"><h3>${safe(f)}</h3>${listaItens(grupos[f],p=>`<div class="item project-card"><b>${safe(p.nome)}</b><div class="meta">Responsável: ${safe(p.responsavel)}<br>Previsão: ${safe(p.previsaoConclusao||'A definir')}<br>Competência: ${safe(p.competencia||'A definir')}</div><p class="project-objective">${safe(p.objetivo||'')}</p>${badge(p.status,'status')}${badge(p.prioridade,'high')}${badge('Progresso: '+safe(p.progresso||'0%'),'progress')}</div>`,'Sem projetos ativos nesta frente.')}</article>`).join('')||vazio('Sem projetos ativos movimentados nesta competência.')}</div>`}
function renderDemandas(arr){return listaItens(arr,x=>`<div class="item"><b>${safe(x.titulo)}</b><div class="meta">${safe(x.periodo)}<br>${safe(x.projeto)}<br>Responsável: ${safe(x.responsavel)}</div><div>${safe(x.resultado)}</div>${badge(x.status,'ok')}</div>`)}
function renderTabela(rows){return rows.length?`<div class="tablewrap"><table><thead><tr><th>Prazo</th><th>Entrega / Pendência</th><th>Projeto</th><th>Responsável</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${safe(x.prazo||x.data||'A definir')}</td><td>${safe(x.pendencia||x.entrega||x.acao)}</td><td>${safe(x.projeto)}</td><td>${safe(x.responsavel)}</td><td>${badge(x.status,'status')}</td></tr>`).join('')}</tbody></table></div>`:vazio('Sem registros para a competência.')}
function render(mes){const tarefas=(DATA.tarefasConcluidas||[]).filter(x=>x.mes===mes||temMes(x.data,mes));const demandas=(DATA.demandasConcluidas||[]).filter(x=>temMes(x.periodo,mes));const incidentes=(DATA.incidentes||[]).filter(x=>temMes(x.abertura,mes)||temMes(x.encerramento,mes));const pendencias=(DATA.pendencias||[]).filter(x=>temMes(x.prazo,mes));const proximas=[...((DATA.proximasEntregas||{}).proximos15Dias||[]),...((DATA.proximasEntregas||{}).concluidosRecentemente||[])].filter(x=>temMes(x.data,mes));const projetos=(DATA.projetos||[]).filter(p=>mesesDoProjeto(p).includes(mes));const comp=(DATA.competencias||[]).find(x=>x.mes===mes)||{};const resumo=comp.atividades||[];let html=`<div class="note"><b>Competência:</b> ${safe(mes)} &nbsp; | &nbsp; <b>Relatório:</b> v${RELATORIO_VERSAO} &nbsp; | &nbsp; <b>Base JSON:</b> v${safe(DATA.versao||'')}<br><b>Base atualizada em:</b> ${safe(DATA.ultimaAtualizacao)}<br><b>Regra do filtro:</b> somente registros com data, período ou competência vinculada ao mês selecionado.</div>`;html+=`<section class="section"><h2>Indicadores da Competência</h2><div class="metrics">${metric('Atividades',tarefas.length)}${metric('Projetos movimentados',projetos.length)}${metric('Demandas concluídas',demandas.length)}${metric('Incidentes',incidentes.length)}${metric('Pendências',pendencias.length)}${metric('Entregas',proximas.length)}</div></section>`;html+=`<section class="section"><h2>Resumo Executivo</h2><article class="panel">${resumo.length?'<ul>'+resumo.map(s=>'<li>'+safe(s)+'</li>').join('')+'</ul>':vazio('Sem resumo executivo registrado para a competência.')}</article></section>`;html+=`<section class="section"><h2>Atividades Concluídas</h2>${renderAtividades(tarefas)}</section>`;html+=`<section class="section"><h2>Projetos Movimentados</h2>${renderProjetos(projetos)}</section>`;html+=`<section class="section"><h2>Demandas Concluídas</h2>${renderDemandas(demandas)}</section>`;html+=`<section class="section"><h2>Pendências e Entregas do Mês</h2>${renderTabela([...pendencias,...proximas])}</section>`;$('app').className='';$('app').innerHTML=html}
function mesesDisponiveis(data){let ms=[];(data.competencias||[]).forEach(c=>ms.push(c.mes));(data.tarefasConcluidas||[]).forEach(t=>{if(t.mes)ms.push(t.mes);ms.push(...mesesDeTexto(t.data))});(data.projetos||[]).forEach(p=>ms.push(...mesesDoProjeto(p)));return [...new Set(ms.filter(Boolean))].sort((a,b)=>mesAnoValor(a)-mesAnoValor(b))}
function iniciar(data){DATA=data;$('jsonVersion').innerText='Base JSON: v'+texto(data.versao||'');$('jsonUpdate').innerText='Atualização: '+texto(data.ultimaAtualizacao||'');const meses=mesesDisponiveis(data);$('competencia').innerHTML=meses.map(m=>`<option value="${safe(m)}">${safe(m)}</option>`).join('');const padrao=(data.competencias||[]).find(x=>/execução|execucao/i.test(texto(x.status)))?.mes||meses[meses.length-1]||'';$('competencia').value=padrao;$('competencia').addEventListener('change',e=>render(e.target.value));render($('competencia').value)}
Promise.all([fetch('dados_painel_aura.json?cache='+Date.now()).then(r=>r.json()),fetch('projetos_extra.json?cache='+Date.now()).then(r=>r.ok?r.json():{}).catch(()=>({}))]).then(([d,e])=>aplicarExtras(d,e)).then(iniciar).catch(()=>{$('app').innerHTML='Erro ao carregar dados do relatório.'});
